[project]
name = "arc-agi-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arc-agi>=0.9.9",
    "pillow>=12.3.0",
    "tensorboard>=2.21.0",
    "torch>=2.13.0",
    "tyro>=1.0.15",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
